sudo: false
cache: pip

language: python
python:
  - "3.6"
  - "3.5"

env:
  - MARSHMALLOW_VERSION="==2.0.0"
  - MARSHMALLOW_VERSION=""

install:
  - travis_retry pip install -U .
  - travis_retry pip install -r dev-requirements.txt
  - travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre

script:
  - pytest
  - flake8 .
